"""Recipe reconstruction — generate and replay reproducible analysis pipelines."""
from __future__ import annotations

import importlib.util
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from databench_mcp.core.findings import _read_findings
from databench_mcp.workspace import project_path, read_manifest


def _recipes_dir(project: str) -> Path:
    return project_path(project) / "recipes"


def _is_url(source: str) -> bool:
    return source.startswith("http://") or source.startswith("https://")


def reconstruct_recipe(project: str) -> dict[str, Any]:
    """Generate recipe.py and recipe_meta.yaml from manifest, findings, and chart sidecars."""
    manifest = read_manifest(project)
    datasets = manifest.get("datasets", {})
    if not datasets:
        raise ValueError("nothing to reconstruct — ingest data first")

    findings = _read_findings(project)

    charts_dir = project_path(project) / "charts"
    chart_sidecars: list[dict] = []
    if charts_dir.exists():
        for sidecar in sorted(charts_dir.glob("*_params.json")):
            try:
                chart_sidecars.append(json.loads(sidecar.read_text(encoding="utf-8")))
            except (json.JSONDecodeError, OSError):
                pass

    body_lines: list[str] = []
    steps: list[dict] = []

    for name, ds in datasets.items():
        source = ds.get("source", "")
        if source == "derived":
            sql = ds.get("sql", "")
            body_lines.append(f"    derive_table(PROJECT, {sql!r}, {name!r})")
            steps.append({
                "kind": "derive_table",
                "params": {"sql": sql, "table_name": name},
                "expected": {"rows": ds.get("row_count"), "columns": ds.get("col_count")},
            })
        elif _is_url(source):
            body_lines.append(f"    ingest_url(PROJECT, {source!r}, table_name={name!r})")
            steps.append({"kind": "ingest_url", "params": {"url": source, "table_name": name}, "expected": None})
        else:
            body_lines.append(f"    ingest_file(PROJECT, {source!r}, table_name={name!r})")
            steps.append({"kind": "ingest_file", "params": {"source": source, "table_name": name}, "expected": None})

        body_lines.append(f"    profile_table(PROJECT, {name!r})")
        steps.append({"kind": "profile_table", "params": {"table": name}, "expected": None})

    for f in findings:
        method = f.get("method", "unknown")
        table = f.get("table", "unknown")
        target = f.get("target")
        features = f.get("features")
        params = f.get("params") or {}

        kwargs = ""
        if target is not None:
            kwargs += f", target={target!r}"
        if features:
            kwargs += f", features={features!r}"
        if params:
            kwargs += f", params={params!r}"

        body_lines.append(f"    run_model(PROJECT, {table!r}, {method!r}{kwargs})")
        steps.append({
            "kind": "run_model",
            "params": {"table": table, "method": method, "target": target,
                       "features": features, "params": params},
            "expected": {"metrics": f.get("metrics", {})},
        })

    existing_finding_ids = {f.get("id") for f in findings}
    skipped: list[str] = []
    for sc in chart_sidecars:
        fid = sc.get("finding_id")
        if fid and fid not in existing_finding_ids:
            skipped.append(str(fid))
            continue
        ct = sc["chart_type"]
        tbl = sc["table"]
        cols = sc.get("columns", [])
        sc_params = sc.get("params") or {}

        kwargs = f", columns={cols!r}"
        if fid:
            kwargs += f", finding_id={fid!r}"
        if sc_params:
            kwargs += f", params={sc_params!r}"

        body_lines.append(f"    create_chart(PROJECT, {ct!r}, {tbl!r}{kwargs})")
        steps.append({"kind": "create_chart", "params": sc, "expected": None})

    recipe_lines = [
        "# Generated by databench-mcp reconstruct_recipe — do not edit manually.",
        "# Run standalone: pip install databench-mcp && python recipe.py",
        "from databench_mcp.core.ingest import load_file as ingest_file, load_url as ingest_url",
        "from databench_mcp.core.eda import derive_table",
        "from databench_mcp.core.profile import profile_table",
        "from databench_mcp.core.modeling import run_model",
        "from databench_mcp.core.viz import create_chart",
        "",
        f"PROJECT = {project!r}",
        "",
        "def run():",
        *body_lines,
        "",
        'if __name__ == "__main__":',
        "    run()",
        "",
    ]
    recipe_py_text = "\n".join(recipe_lines)

    meta: dict[str, Any] = {
        "project": project,
        "reconstructed_at": datetime.now(timezone.utc).isoformat(),
        "tolerances": {"numeric_rtol": 1.0e-5, "numeric_atol": 1.0e-8},
        "steps": steps,
        "last_run": None,
    }

    recipes_dir = _recipes_dir(project)
    recipes_dir.mkdir(exist_ok=True)
    recipe_py_path = recipes_dir / "recipe.py"
    recipe_meta_path = recipes_dir / "recipe_meta.yaml"

    overwrite_warning = "recipe.py already existed and was overwritten" if recipe_py_path.exists() else None
    recipe_py_path.write_text(recipe_py_text, encoding="utf-8")
    recipe_meta_path.write_text(yaml.dump(meta, default_flow_style=False, allow_unicode=True), encoding="utf-8")

    all_warnings = [w for w in [overwrite_warning] + [f"skipped chart referencing missing finding '{fid}'" for fid in skipped] if w]
    return {
        "recipe_py": str(recipe_py_path),
        "meta_yaml": str(recipe_meta_path),
        "steps": len(steps),
        "warning": "; ".join(all_warnings) if all_warnings else None,
    }


def _diff_step(
    expected: Any, actual: Any, rtol: float, atol: float
) -> tuple[float | None, bool]:
    """Returns (delta_or_None, passed)."""
    if isinstance(expected, float) and isinstance(actual, (int, float)):
        delta = abs(float(actual) - float(expected))
        return delta, delta <= atol + rtol * abs(float(expected))
    if isinstance(expected, int) and isinstance(actual, int):
        return float(abs(actual - expected)), actual == expected
    return None, expected == actual


def run_recipe(project: str, diff_mode: bool = True) -> dict[str, Any]:
    """Execute recipe.py and optionally diff outputs against expected in recipe_meta.yaml."""
    recipes_dir = _recipes_dir(project)
    recipe_py_path = recipes_dir / "recipe.py"
    recipe_meta_path = recipes_dir / "recipe_meta.yaml"

    if not recipe_py_path.exists():
        raise FileNotFoundError(
            f"No recipe found for project '{project}' — run reconstruct_recipe first"
        )
    if not recipe_meta_path.exists():
        raise FileNotFoundError(
            f"No recipe_meta.yaml found for project '{project}' — run reconstruct_recipe first"
        )

    meta = yaml.safe_load(recipe_meta_path.read_text(encoding="utf-8")) or {}
    first_run = meta.get("last_run") is None

    existing_ids = {f.get("id") for f in _read_findings(project)}

    try:
        spec = importlib.util.spec_from_file_location("_recipe_run", recipe_py_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        module.run()
    except Exception as exc:
        return {
            "status": "error",
            "steps_run": 0,
            "changes": [],
            "finding_ids": [],
            "error": str(exc),
        }

    new_findings = [f for f in _read_findings(project) if f.get("id") not in existing_ids]
    new_finding_ids = [f["id"] for f in new_findings]

    steps = meta.get("steps", [])
    tolerances = meta.get("tolerances", {})
    rtol = float(tolerances.get("numeric_rtol", 1e-5))
    atol = float(tolerances.get("numeric_atol", 1e-8))

    run_model_steps = [s for s in steps if s.get("kind") == "run_model"]

    def _update_and_save(findings: list[dict]) -> None:
        for i, finding in enumerate(findings):
            if i < len(run_model_steps):
                run_model_steps[i]["expected"] = {"metrics": finding.get("metrics", {})}
        meta["last_run"] = {
            "at": datetime.now(timezone.utc).isoformat(),
            "finding_ids": new_finding_ids,
        }
        recipe_meta_path.write_text(
            yaml.dump(meta, default_flow_style=False, allow_unicode=True),
            encoding="utf-8",
        )

    if not diff_mode or first_run:
        _update_and_save(new_findings)
        return {
            "status": "clean",
            "steps_run": len(steps),
            "changes": [],
            "finding_ids": new_finding_ids,
            "error": None,
        }

    if len(new_findings) != len(run_model_steps):
        return {
            "status": "error",
            "steps_run": len(steps),
            "changes": [],
            "finding_ids": new_finding_ids,
            "error": (
                f"finding count mismatch: expected {len(run_model_steps)} "
                f"model step(s), got {len(new_findings)}"
            ),
        }

    changes: list[dict] = []
    for step_idx, (step, finding) in enumerate(zip(run_model_steps, new_findings)):
        expected_metrics = (step.get("expected") or {}).get("metrics", {})
        actual_metrics = finding.get("metrics", {})
        for field, expected_val in expected_metrics.items():
            actual_val = actual_metrics.get(field)
            if actual_val is None:
                changes.append({
                    "step": step_idx, "kind": "run_model", "field": field,
                    "expected": expected_val, "actual": None, "delta": None,
                })
                continue
            delta, passed = _diff_step(expected_val, actual_val, rtol, atol)
            if not passed:
                changes.append({
                    "step": step_idx, "kind": "run_model", "field": field,
                    "expected": expected_val, "actual": actual_val, "delta": delta,
                })

    if not changes:
        _update_and_save(new_findings)

    return {
        "status": "changed" if changes else "clean",
        "steps_run": len(steps),
        "changes": changes,
        "finding_ids": new_finding_ids,
        "error": None,
    }
